/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: catl3rs (https://sketchfab.com/catwithantlers)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/banana-duck-e542871d099947de88212a4a86315a40
title: banana duck
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/duck.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[0.02, 0.37, -0.01]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={[0.3, 1.84, 0.3]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_5.geometry}
              material={materials.body}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_7.geometry}
              material={materials.eyes}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_6.geometry}
              material={materials.beak}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_4.geometry}
              material={materials.banana_peel}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/duck.gltf");