/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: mRiot (https://sketchfab.com/malgorzatariot)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/forest-diorama-1e89d7e0312b4cb48f5e2364692e76ac
title: Forest Diorama
*/

import React, { useRef } from "react";
import { PerspectiveCamera, RenderTexture, useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/forest_diorama.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.ROUND_ATLAS}
        >
          <RenderTexture attach="map">
          <PerspectiveCamera makeDefault position={[0,0,5]} />
          </RenderTexture>
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/forest_diorama.gltf");
