/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: VARRRG (https://sketchfab.com/VladislavFehu)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/love-low-poly-dd3b881a34904991878dc6a5a05aa1f6
title: Love Low Poly
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/love.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, 0, 33.42]}>
          <group position={[0, 0, -33.42]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_3.geometry}
              material={materials.Material_30}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/love.gltf");